#drop table EMPLEADOS;

#drop table PROYECTOS;

#drop table ASIG_PROYECTOS;

create table EMPLEADOS 
(
 DNI_NIF varchar(9) NOT NULL,
 NOMBRE varchar(32) NOT NULL,PRIMARY KEY(DNI_NIF));

create table PROYECTOS 
(
 NUM_PROY INTEGER AUTO_INCREMENT NOT NULL,
 NOMBRE varchar(32) NOT NULL, DNI_NIF_JEFE_PROY CHAR(9) NOT NULL,
 F_INICIO DATE NOT NULL, F_FIN DATE, PRIMARY KEY(NUM_PROY),FOREIGN KEY
    FK_PROY_JEFE(DNI_NIF_JEFE_PROY) REFERENCES EMPLEADOS(DNI_NIF));
    
create table ASIG_PROYECTOS(DNI_NIF_EMP CHAR(9),NUM_PROY INTEGER NOT NULL,F_INICIO DATE NOT NULL, F_FIN DATE,PRIMARY KEY(DNI_NIF_EMP,NUM_PROY,F_INICIO),FOREIGN KEY F_ASIG_EMP(DNI_NIF_EMP)REFERENCES EMPLEADOS(DNI_NIF),FOREIGN KEY F_ASIG_PROY(NUM_PROY)REFERENCES PROYECTOS(NUM_PROY));


